kind: pipeline
name: default

steps:
  - name: bild and test
    image: gradle:7.4.2-jdk17
    commands:
      - gradle build
    when:
      branch:
        include:
          - bugfix/*
          - feature/*
          - main
      event:
        include:
          - push
          - pull_request

  - name: build image
    image: gradle:7.4.2-jdk17
    commands:
      - gradle bootBuildImage --imageName=192.168.178.10:10130/schedario-svc:latest --publishImage
    when:
      branch:
        include:
          - main
