kind: pipeline
name: default

steps:
  - name: 'build & test'
    image: gradle:7.4.2-jdk17
    commands:
      - gradle build
    when:
      branch:
        include:
          - bugfix/*
          - feature/*
          - main
      event:
        include:
          - push
          - pull_request
