schedario:
  archive:
    path: '/home/mav/Development/schedario/schedario-svc/src/test/resources/test-archive'
    scanner:
      cron: '1 * * * * *'
  database:
    cleaner:
      cron: '1 * * * * *'
    updater:
      cron: '1 * * * * *'